obj-m += intrKeyLog.o
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
test:
	sudo dmesg -C
	sudo insmod intrKeyLog.ko
	sudo rmmod  intrKeyLog.ko
	dmesg

