obj-m += dedicated_q.o
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
test:
	sudo dmesg -C
	sudo insmod dedicated_q.ko
	sudo rmmod  dedicated_q.ko
	dmesg

